network_dhcp_server_subnet: ''
network_dhcp_server_netmask: ''
network_dhcp_server_prefix: ''
network_dhcp_server_length: ''
network_dhcp_server_domain: ''
network_dhcp_server_domain_name_servers: ''
network_dhcp_server_router_ip: ''
network_dhcp_server_lease_time: '86400'
network_dhcp_server_wifi_controller_ip: ''