- hosts: all
  gather_facts: false
  collections:
    - zpe.nodegrid

  tasks:
  - name: Create template_nodegrid
    zpe.nodegrid.managed_devices:
      device:
        access:
          name: "_template_nodegrid2"
          type: "console_server_nodegrid"
          description: "template console server nodegrid"
          ip_address: "localhost"
          port: ""
          address_location: ""
          coordinates: ""
          web_url: "http://%IP"
          launch_url_via_html5: "yes"
          method: "internal_browser"
          method: "browser_extension_forwarder"
          credential: "set_now"
          username: "admin"
          password: "adsf"
          #credential: "ask_during_login"
          allow_pre-shared_ssh_key: "no"
          enable_device_state_detection_based_on_network_traffic: "yes"
          enable_hostname_detection: "no"
          multisession: "yes"
          read-write_multisession: "no"
          enable_send_break: "no"
          break_sequence: "~break"
          icon: "zpe.png"
          mode: "on-demand"
          expiration: "never"
          expiration: "date"
          expiration_date: ""
          expiration: "days"
          duration: ""
          end_point: "appliance"
          end_point: "serial_port"
          port_number: ""
          end_point: "usb_port"
          port_number: ""
          end_point: "kvm_port"
          port_number: ""
          end_point: "pdu_port"
          port_number: ""
          skip_authentication_to_access_device: "no"
          skip_authentication_in_ssh_sessions: "yes"
          skip_authentication_in_telnet_sessions: "yes"
          skip_authentication_in_raw_sessions: "yes"
          skip_authentication_in_web_sessions: "yes"
          escape_sequence: "^Ec"
          power_control_key: "^O"
          show_text_information: "yes"
          enable_ip_alias: "no"
          ip_alias: ""
          interface: "lanbrd"
          ip_alias_browser_action: "console"
          ip_alias_telnet: "yes"
          ip_alias_telnet_port: "23"
          ip_alias_binary: "no"
          ip_alias_binary_port: ""
          enable_second_ip_alias: "no"
          sec_ip_alias: ""
          sec_interface: "lanbrd"
          sec_ip_alias_browser_action: "console"
          sec_ip_alias_telnet: "yes"
          sec_ip_alias_telnet_port: "23"
          sec_ip_alias_binary: "no"
          sec_ip_alias_binary_port: ""
          allow_ssh_protocol: "yes"
          ssh_port: ""
          allow_telnet_protocol: "no"
          telnet_port: ""
          allow_binary_socket: "no"
          tcp_socket_port: ""
