- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - zpe.nodegrid

  tasks:
  - name: Import Managed Devices
    zpe.nodegrid.import_devices:
      csv_ansible_devices: ./example/csv_ansible_devices.csv
      csv_ip_based: ./example/csv_ip_based.csv
      csv_local: ./example/csv_local.csv
      csv_usb: ./example/csv_usb.csv
      ansible_inventory_path: ./inventories
      ansible_inventory_hosts_filename: imported_managed_devices.yaml
      custom_fields_prefix: cf_

