- hosts: all
  gather_facts: false
  collections:
    - zpe.nodegrid

  tasks:

    - name: Add ipv4 DHCP Network range
      zpe.nodegrid.dhcp_server:
        network_range:
          subnet: '203.0.113.0'
          netmask: '255.255.255.0'
          ip_address_start: '203.0.113.100'
          ip_address_end: '203.0.113.150'

    - name: Add ipv6 DHCP Network range
      zpe.nodegrid.dhcp_server:
        network_range:
          prefix: "2001:db8::"
          length: '32'
          ip_address_start: '2001:db8::1000'
          ip_address_end: '2001:db8::1063'