- hosts: all
  gather_facts: false
  collections:
    - zpe.nodegrid

  tasks:
  - name: Set Network Settings
    zpe.nodegrid.network:
      settings:
        hostname: "remote-site"
        ipv4_loopback: "10.0.0.1"
