- hosts: all
  gather_facts: false
  collections:
    - zpe.nodegrid

  tasks:

    - name: Add ipv4 DHCP Host
      zpe.nodegrid.dhcp_server:
        host:
          subnet: '203.0.113.0'
          netmask: '255.255.255.0'
          hostname: 'myhostname'
          hw_address: 'e4:1a:2c:00:00:01'
          ip_address: '203.0.113.120'
          # agent_circuit_id: ''
          # assigned_hostname: ''
    
    - name: Add ipv6 DHCP Host
      zpe.nodegrid.dhcp_server:
        host:
          prefix: "2001:db8::"
          length: '32'
          hostname: 'myhostname2'
          duid: 'e4:1a:2c:00:00:01'
          ip_address: '2001:db8::1050'