- hosts: all
  gather_facts: no
  gather_timeout: 30
  collections:
    - ansible.builtin
    - zpe.nodegrid

  tasks:
    - name: Setup wireguard Mesh Peer
      zpe.nodegrid.wireguard:
        mesh_peer:
          interface_name: mesh1
          interface_type: mesh # optional
          peer_name: wg-peer-mesh1
          allowed_ips: 10.1.1.2/32
          external_address: 192.100.1.25
          listening_port: 51820
          keepalive: 10
          public_key: '2Kl6LY2vAKzavX95HZiSNNRoLusi+fWDU5777777777='
          description: "mesh peer to remote wireguard mesh endpoint"
