- hosts: all
  gather_facts: no
  collections:
    - ansible.builtin
    - zpe.nodegrid

  tasks:
    - name: Setup wireguard Server Endpoint
      zpe.nodegrid.wireguard:
        server_endpoint:
          interface_name: wg-server1
          interface_type: server # optional
          internal_address: 10.1.1.1/32
          listening_port: 51830
          keepalive: 10
          keypair: 'auto_generate' # auto_generate, input_manually
          private_key: 'KDjRVwxo1CQpjaRzz/WrFLpSex2HFlbwF7777777777=' # keypair = input_manually
          public_key: '+oR/P4IZwC2/LvU7YbZ8LoXqSsjbKdljLb777777777=' # keypair = input_manually
          generate_keys: no # yes: regenare the keys
          status: enabled # enabled (default) or disabled
          description: "Server endpoint to accept remote wireguard client endpoints"
