# ##############################
# Hub - Create Hub Wireguard Server endpoint - VPN
- name: Setup wireguard Server Endpoint
  zpe.nodegrid.wireguard:
    server_endpoint:
      interface_name: "{{ hostvars[inventory_hostname].wireguard_interface_name }}"
      interface_type: server
      internal_address: "{{ hostvars[inventory_hostname].wireguard_interface_address }}"
      listening_port: "{{ hostvars[inventory_hostname].wireguard_udp_port }}"
      keepalive: "{{ hostvars[inventory_hostname].wireguard_keepalive | default(20) }}"
      keypair: 'auto'
      status: enabled # enabled (default) or disabled
      description: "Server endpoint for Coordinator {{ inventory_hostname }}"

- name: Get Hub Wireguard Public Key
  tags: always
  zpe.nodegrid.nodegrid_cmds:
    cmds:
    - cmd: 'show /settings/wireguard/{{ hostvars[inventory_hostname].wireguard_interface_name }}/interfaces/ public_key'
  register: wg_public_key
- name: Export Hub Wireguard Public Key
  tags: always
  set_fact:
    wireguard_public_key: "{{ wg_public_key.cmds_output[0]['stdout_lines'][1].split('= ')[1] }}"

- name: Create empty fact for Peer List
  tags: always
  set_fact:
    wireguard_interfaces_peers: []
