# #####################################
# Spoke - Create Spoke Wireguard VPN
- name: Create Spoke Wireguard VPN
  tags: always
  vars:
    _peer_name: "peer-{{ wg_tunnel.wireguard_hub }}"
  block:
    - name: Setup Wireguard Client Endpoint
      zpe.nodegrid.wireguard:
        client_endpoint:
          interface_type: client
          interface_name: "{{ wg_tunnel.wireguard_interface_name }}"
          internal_address: "{{ wg_tunnel.wireguard_interface_address }}"
          keepalive: 10
          keypair: 'auto_generate' # auto, input_manually
          status: enabled # enabled (default) or disabled
          description: "Client endpoint to peer with remote wireguard coordinator {{ wg_tunnel.wireguard_hub }}"

    - name: Get Spoke Wireguard Public Key
      tags: always
      zpe.nodegrid.nodegrid_cmds:
        cmds:
        - cmd: 'show /settings/wireguard/{{ wg_tunnel.wireguard_interface_name }}/interfaces/ public_key'
      register: wg_public_key

    - name: Set Peer Value
      tags: always
      set_fact:
        wireguard_interfaces_peer_tmp:
          - 'peer_name': "{{ nodegrid_hostname }}"
            'public_key' : "{{ wg_public_key.cmds_output[0]['stdout_lines'][1].split('= ')[1] }}"
            'allowed_ips': "{{ wg_tunnel.wireguard_interface_address }}"

    - name: Export Spoke Wireguard Public Key and assign to Hub
      tags: always
      set_fact:
        wireguard_interfaces_peers: "{{ hostvars[wg_tunnel.wireguard_hub].wireguard_interfaces_peers + wireguard_interfaces_peer_tmp }}"
      delegate_to: "{{ wg_tunnel.wireguard_hub }}"
      delegate_facts: true
      when: wg_tunnel.wireguard_hub in query('inventory_hostnames', ansible_limit | default('all'))

    - name: Setup Wireguard Peer
      zpe.nodegrid.wireguard:
        client_peer:
          interface_name: "{{ wg_tunnel.wireguard_interface_name }}"
          interface_type: client # optional
          peer_name: "{{ _peer_name }}"
          allowed_ips: "{{ hostvars[wg_tunnel.wireguard_hub].wireguard_interface_address}}"
          external_address: "{{ hostvars[wg_tunnel.wireguard_hub].wireguard_external_address_main }}"
          listening_port: "{{ hostvars[wg_tunnel.wireguard_hub].wireguard_udp_port }}"
          keepalive: 10
          public_key: "{{ hostvars[wg_tunnel.wireguard_hub].wireguard_public_key }}"
          description: "{{ wg_tunnel.wireguard_interface_name }} peering with {{ hostvars[wg_tunnel.wireguard_hub].wireguard_interface_name }}"
