# ##############################
# Hub - Add hub-spoke peering
- name: Create HUB Wireguard Peers
  tags: always
  vars:
    _peer_name: "peer-{{ wg_peer.peer_name }}"
  block:
    - name: Setup Wireguard Peer
      zpe.nodegrid.wireguard:
        server_peer:
          interface_name: "{{ hostvars[inventory_hostname].wireguard_interface_name }}"
          interface_type: server # optional
          peer_name: "{{ _peer_name }}"
          allowed_ips: "{{ wg_peer.allowed_ips }}"
          keepalive: 10
          public_key: "{{ wg_peer.public_key }}"
          description: "{{ wireguard_interface_name }} peering with {{ wg_peer.peer_name }}"

    - name: check if Peer Port 22 is accessible
      tags: always
      wait_for:
        host: "{{ wg_peer.allowed_ips.split('/') | first }}"
        port: 22
        state: started
        delay: 20
        timeout: 300
