- hosts: all
  gather_facts: false
  collections:
    - zpe.nodegrid

  tasks:
    - name: Apply Firewall Settings
      zpe.nodegrid.firewall:
         ipv4_nat: "{{ ipv4_nat }}"
         ipv4_firewall: "{{ ipv4_firewall }}"
         debug: True
      register: output

    - name: Display stdout_line Result
      debug:
        msg: "{{ output }}"