- name: Iteration "{{ i }}" | Add "{{ devices | length | default('') }}" Managed Devices (batch_size= "{{ batch_size }}")
  tags: always
  zpe.nodegrid.managed_devices_bulk_import:
    devices: "{{ devices }}"
    timeout: "{{ nodegrid_timeout | default(60) }}"
  register: result
  until: "'msg' not in result or 'The system configuration has been changed. Please revert.' not in result['msg']"
  retries: "{{ add_device_retires | default(3) }}"
  delay: "{{ add_device_delay | default(0) }}" 
