- name: Configure Nodegrid Failover
  tags: always
  zpe.nodegrid.network:
    settings:
      enable_network_failover: "{{ failover_enable_network_failover }}"
      primary_connection: "{{ failover_primary_connection }}"
      primary_connection_sim_card: "{{ failover_primary_connection_sim_card }}"
      secondary_connection: "{{ failover_secondary_connection }}"
      secondary_connection_sim_card: "{{ failover_secondary_connection_sim_card }}"
      trigger_failed_retries: "{{ failover_trigger_failed_retries }}"
      trigger_successful_retries_to_recover: "{{ failover_trigger_successful_retries_to_recover }}"
      interval_between_retries: "{{failover_interval_between_retries}}"
      enable_primary_failover_by_ip_address: "{{ failover_enable_primary_failover_by_ip_address }}"
      trigger: "{{ failover_trigger }}"
      trigger_ip_address: "{{ failover_trigger_ip_address }}"
      enable_primary_failover_by_signal_strength: "{{ failover_enable_primary_failover_by_signal_strength }}"
      enable_primary_failover_by_data_usage: "{{ failover_enable_primary_failover_by_data_usage }}"
      enable_primary_failover_by_schedule: "{{ failover_enable_primary_failover_by_schedule }}"
      enable_primary_sim_failback_by_schedule: "{{ failover_enable_primary_sim_failback_by_schedule }}"
      enable_third_level_network_failover: "{{ failover_enable_third_level_network_failover }}"
      enable_secondary_failover_by_ip_address: "{{ failover_enable_secondary_failover_by_ip_address }}"
      secondary_trigger: "{{ failover_secondary_trigger }}"
      enable_secondary_failover_by_signal_strength: "{{ failover_enable_secondary_failover_by_signal_strength }}"
      enable_secondary_failover_by_data_usage: "{{ failover_enable_secondary_failover_by_data_usage }}"
      enable_secondary_failover_by_schedule: "{{ failover_enable_secondary_failover_by_schedule }}"
      enable_secondary_sim_failback_by_schedule: "{{ failover_enable_secondary_sim_failback_by_schedule }}"
