- name: Update System Services
  tags: always
  zpe.nodegrid.import_settings:
    cmds:
      - "/settings/services enable_snmp_service={{ services_enable_snmp_service }}"
      - "/settings/services enable_https_file_repository={{ services_enable_https_file_repository }}"
      - "/settings/services enable_telnet_service_to_nodegrid={{ services_enable_telnet_service_to_nodegrid }}"
      - "/settings/services enable_telnet_service_to_managed_devices={{ services_enable_telnet_service_to_managed_devices }}"
      - "/settings/services enable_icmp_echo_reply={{ services_enable_icmp_echo_reply }}"
      - "/settings/services enable_icmp_secure_redirects={{ services_enable_icmp_secure_redirects }}"
      - "/settings/services enable_usb_over_ip={{ services_enable_usb_over_ip }}"
      - "/settings/services enable_elasticsearch={{ services_enable_elasticsearch }}"
      - "/settings/services enable_telegraf={{ services_enable_telegraf }}"
      - "/settings/services enable_vmware_manager={{ services_enable_vmware_manager }}"
      - "/settings/services enable_vm_serial_access={{ services_enable_vm_serial_access }}"
      - "/settings/services enable_zero_touch_provisioning={{ services_enable_zero_touch_provisioning }}"
      - "/settings/services enable_bluetooth={{ services_enable_bluetooth }}"
      - "/settings/services enable_pxe={{ services_enable_pxe }}"
      - "/settings/services enable_autodiscovery={{ services_enable_autodiscovery }}"
      - "/settings/services block_host_with_multiple_authentication_fails={{ services_block_host_with_multiple_authentication_fails }}"
      - "/settings/services period_host_will_stay_blocked={{ services_period_host_will_stay_blocked }}"
      - "/settings/services timeframe_to_monitor_authentication_fails={{ services_timeframe_to_monitor_authentication_fails }}"
      - "/settings/services number_of_authentication_fails_to_block_host={{ services_number_of_authentication_fails_to_block_host }}"
      - "/settings/services allow_root_console_access={{ services_allow_root_console_access }}"
      - "/settings/services rescue_mode_require_authentication={{ services_rescue_mode_require_authentication }}"
      - "/settings/services password_protected_boot={{ services_password_protected_boot }}"
      - "/settings/services enable_docker={{ services_enable_docker }}"
      - "/settings/services enable_qemu|kvm={{ services_enable_qemu }}"
