- hosts: all
  gather_facts: false
  collections:
    - zpe.nodegrid

  tasks:
  - name: Add local account
    no_log: True
    zpe.nodegrid.security:
        local_account:
          username: "<myusername>"
          password: "<mypassword>"
          account_type: "regular_account"
          password_change_at_login: "no"
          user_group: "admin"
