- hosts: all
  gather_facts: false
  collections:
    - zpe.nodegrid

  tasks:
  - name: Update password rules
    zpe.nodegrid.security:
        password_rules:
          check_password_complexity: "no"
          pwd_expiration_min_days: "0"
          pwd_expiration_max_days: "99999"
          pwd_expiration_warning_days: "7"