- hosts: all
  gather_facts: false
  collections:
    - zpe.nodegrid

  tasks:
  - name: Add local account
    zpe.nodegrid.security:
        local_account:
          username: "your_username"
          password: "your_password"
          account_type: "regular_account"
          password_change_at_login: "no"
          user_group: "admin"