# Process the xlsx file on the localhost and create the Ansible inventory
- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.builtin
    - zpe.nodegrid
  tasks:
  - name: Process the Nodegrid Importer Template xlsx file
    tags: process-xlsx-managed-devices
    vars:
      nodegrid_importer_template_xlsx: './Nodegrid_Importer_Template.xlsx'
    include_role:
      name: process_managed_devices_into_inventory
