# [TODO] Updated playbook with check for device type
- name: Update Serial Port Settings
  tags: always
  zpe.nodegrid.managed_devices:
    device:
      access:
        name: "{{ item.name }}"
        description: "{{ item.description | default('') }}"
        port_name: "ttyS{{ item.port_number | default('1') }}"
        type: "{{ item.type | default('local_serial') }}"
        baud_rate: "{{ item.baud_rate | default('Auto') }}"
        parity: "{{ item.parity | default('None') }}"
        flow_control: "{{ item.flow_control | default('None') }}"
        data_bits: "{{ item.data_bits | default('8') }}"
        stop_bits: "{{ item.stop_bits | default('1') }}"
        rs-232_signal_for_device_state_detection: "{{ item.rs_232_signal_for_device_state_detection | default('Auto') }}"
        enable_device_state_detection_based_in_data_flow: "{{ item.enable_device_state_detection_based_in_data_flow | default('no') }}"
        data_flow_scan_interval: "{{ item.data_flow_scan_interval | default('3') }}"
        multisession: "{{ item.multisession | default('yes') }}"
        read-write_multisession: "{{ item.read_write_multisession | default('no') }}"
        enable_serial_port_settings_via_escape_sequence: "{{ item.enable_serial_port_settings_via_escape_sequence | default('yes') }}"
        icon: "{{ item.icon | default('terminal.png') }}"
        mode: "{{ item.mode | default('enabled') }}" 
        allow_ssh_protocol: "{{ item.allow_ssh_protocol | default('yes') }}"
        ssh_port: "{{ item.ssh_port | default('') }}"
        allow_telnet_protocol: "{{ item.allow_telnet_protocol | default('no') }}"
        telnet_port: "{{ item.telnet_port | default('') }}"
  with_items: "{{ serial_ports }}"
  when:
    - ansible_facts is defined and ansible_facts.nodegrid_about is defined
    - ansible_facts.nodegrid_about.model is defined and ansible_facts.nodegrid_about.model != "NSR"
    - serial_ports is defined

- name: Update Serial Port Settings on NSR
  tags: always
  zpe.nodegrid.managed_devices:
    device:
      access:
        name: "{{ item.name }}"
        port_name: "ttyS{{ item.slot_number | default('1') }}-{{ item.port_number | default('1') }}"
        type: "{{ item.type | default('local_serial') }}"
        baud_rate: "{{ item.baud_rate | default('Auto') }}"
        parity: "{{ item.parity | default('None') }}"
        flow_control: "{{ item.flow_control | default('None') }}"
        data_bits: "{{ item.data_bits | default('8') }}"
        stop_bits: "{{ item.stop_bits | default('1') }}"
        rs-232_signal_for_device_state_detection: "{{ item.rs_232_signal_for_device_state_detection | default('Auto') }}"
        enable_device_state_detection_based_in_data_flow: "{{ item.enable_device_state_detection_based_in_data_flow | default('no') }}"
        data_flow_scan_interval: "{{ item.data_flow_scan_interval | default('3') }}"
        multisession: "{{ item.multisession | default('yes') }}"
        read-write_multisession: "{{ item.read_write_multisession | default('no') }}"
        enable_serial_port_settings_via_escape_sequence: "{{ item.enable_serial_port_settings_via_escape_sequence | default('yes') }}"
        icon: "{{ item.icon | default('terminal.png') }}"
        mode: "{{ item.mode | default('enabled') }}"
        allow_ssh_protocol: "{{ item.allow_ssh_protocol | default('yes') }}"
        ssh_port: "{{ item.ssh_port | default('') }}"
        allow_telnet_protocol: "{{ item.allow_telnet_protocol | default('no') }}"
        telnet_port: "{{ item.telnet_port | default('') }}"
  with_items: "{{ serial_ports }}"
  when:
    - ansible_facts is defined and ansible_facts.nodegrid_about is defined
    - ansible_facts.nodegrid_about.model is defined and ansible_facts.nodegrid_about.model == "NSR"
    - serial_ports is defined
