- name: deploy the spoke wg config
  hosts: spokes
  become: true
#
#  vars_files:
#    - ./spoke-variables.yaml

  tasks:
  - name: Create the user API script
    template:
      src: "createuser.cli.j2"
      dest: "/tmp/createuser.cli"
    tags:
      - apiuser
  - name: Create the API user
    ansible.builtin.shell: sudo su -c "cat /tmp/createuser.cli | cli"
    register: api_results
    tags:
      - apiuser
  - name: Show user API results
    debug:
      var: api_results.stdout_lines
    tags:
      - apiuser
  - name: Save user API key to file
    copy:
      content: "{{ api_results.stdout.split(': ')[1] }}"
      dest: "{{ lookup('env', 'PWD') }}/userkey.txt"
    tags:
      - apiuser
  - name: Export user API key to hub-variables
    set_fact:
      NODEGRID_KEY: "{{ api_results.stdout.split(': ')[1] }}"
    tags:
      - apiuser

  - name: Copy project code to Spoke
    copy:
      src: "{{ LOCAL_PROJECT_HOME }}"
      dest: "{{ PROJECT_HOME }}"
        #      remote_src: yes

  - name: Install reqs into the specified virtualenv using Python3
    ansible.builtin.pip:
      requirements: "{{ PROJECT_HOME }}/{{ PROJECT_NAME }}/requirements.txt"
      virtualenv: "{{ PROJECT_HOME }}/{{ PROJECT_NAME }}/{{ PROJECT_VENV }}"
      virtualenv_command: "python3 -m venv"

  - name: spoke-config.yaml config file
    template:
      src: "spoke-config.yaml.j2"
      dest: "{{ PROJECT_HOME }}/{{ PROJECT_NAME }}/config.yaml"

  - name: Changing perm of "{{ PROJECT_HOME }}/{{ PROJECT_NAME }}/wgpeer.py", adding "+x"
    file: dest="{{ PROJECT_HOME }}/{{ PROJECT_NAME }}/wgpeer.py" mode=a+x

  - name: Execute the Spoke Configuration
    ansible.builtin.shell: |
      cd "{{ PROJECT_HOME }}/{{ PROJECT_NAME }}" &&
      source "{{ PROJECT_HOME }}/{{ PROJECT_NAME }}/venv/bin/activate" &&
      "{{ PROJECT_HOME }}/{{ PROJECT_NAME }}/wgpeer.py"
    register: results
    tags:
      - execute
  - name: Show Peering Results
    debug:
      var: results.stdout_lines
    tags:
      - execute
      - executeping

  - name: Execute Ping
    ansible.builtin.shell: "ping -c 5 `ip --json route show  dev {{ WIREGUARD_IFACE_NAME }} | jq -r .[0].dst`"
    register: results
    tags:
      - execute
      - executeping
  - name: Show ping results
    debug:
      var: results.stdout_lines
    tags:
      - execute
      - executeping