- name: Apply Auditing Settings
  tags: always
  zpe.nodegrid.auditing:
     auditing_settings: "{{ auditing_settings | default({}) }}"
     events_zpe_cloud: "{{ events_zpe_cloud | default({}) }}"
     events_email: "{{ events_email | default({}) }}"
     events_file: "{{ events_file | default({}) }}"
     events_syslog: "{{ events_syslog | default({}) }}"
     events_snmp: "{{ events_snmp | default({}) }}"
     event_list: "{{ event_list | default({}) }}"
     destinations_file: "{{ destinations_file | default({}) }}"
     destinations_syslog: "{{ destinations_syslog | default({}) }}"
     destinations_snmp: "{{ destinations_snmp | default({}) }}"
     destinations_email: "{{ destinations_email | default({}) }}"