# Section - REQUIRED - THIS SECTION CONTAINS VALUES THAT MUST BE ADJUSTED
# License Keys: (REQUIRED - ADD VALID CLUSTER LICENSE KEY)
nodegrid_license_keys:
     - XXXXX-XXXXX-XXXXX-XXXXX
     - XXXXX-XXXXX-XXXXX-XXXXX

# Local User Accounts: (REQUIRED - UPDATED PASSWORD)
local_user_accounts:
  - username: admin
    hash_format_password: "no"
    password: "ZPESystems2023!"
    user_group: "admin"

# SECTION - CHANGE - CHANGES ARE RECOMMENDED BUT NOT REQUIRED

# Firmware Settings: (CHANGE - TO DESIRED NODEGRID VERSION)
nodegrid_iso_location: "/var/local/file_manager/datastore/"
nodegrid_iso_file: "Nodegrid_Platform_v5.8.16_20231107.iso"
nodegrid_target_version: "5.8.16"

# Default System Settings: (CHANGE - TO DESIRED VALUES)
sys_show_hostname_on_webui_header: "yes"
sys_idle_timeout: 3600
sys_banner: '''  
WARNING: This private system is provided for authorized use only and it may be monitored for all lawful purposes to ensure its use. All information  
including personal information, placed on or sent over this system may be  
monitored and recorded. Use of this system, authorized or unauthorized,  
constitutes consent to monitoring your session. Unauthorized use may subject you to criminal prosecution. Evidence of any such unauthorized  
use may be used for administrative, criminal and/or legal actions. '''

# Default System Date and Time: (CHANGE - TO DESIRED VALUES)
sys_date_and_time_date_and_time: "network_time_protocol"
sys_date_and_time_zone: "utc"

# Authentication
# Local User Groups: (CHANGE - TO DESIRED VALUES)
nodegrid_local_user_groups:
  - name: 'admin'
    track_system_information: "yes"
    terminate_sessions: "yes"
    software_upgrade_and_reboot_system: "yes"
    configure_system: "yes"
    configure_user_accounts: "yes"
    apply_and_save_settings: "yes"
    shell_access: "yes"
    manage_devices_permissions: "no"
  - name: 'user'
    track_system_information: "no"
    terminate_sessions: "no"
    software_upgrade_and_reboot_system: "no"
    configure_system: "yes"
    configure_user_accounts: "no"
    apply_and_save_settings: "no"
    shell_access: "no"
    manage_devices_permissions: "no"

# Default Authentication Server: (CHANGE - TO DESIRED VALUES)
nodegrid_authentication_servers:
            - number: 1
              method: "tacacs+"
              two_factor_authentication: "none"
              status: "disable"
              fallback_if_denied_access: "yes"
              remote_server: "10.1.1.5"
              tacacs_plus_accounting_server: "10.1.1.5"
              authorize_ssh_pkey_users: "yes"
              tacacs_plus_port: "49"
              tacacs_plus_service: "raccess"
              tacacs_plus_secret: "tacacs"
              tacacs_plus_timeout: "2"
              tacacs_plus_retries: "2"
              tacacs_plus_version: "v1"
              tacacs_plus_enable_user_level: "yes"
              tacacs_plus_user_level_12: "user"
              tacacs_plus_user_level_15: "admin"

# System SNMP Settings: (CHANGE - TO DESIRED VALUES)
sys_snmp_syscontact: "noc@zpesystems.internal"
sys_snmp_syslocation: "Nodegrid"
sys_snmp_two_community: "public"
sys_snmp_two_version: "version_v1|v2"
sys_snmp_two_source: "default"
sys_snmp_two_access_type: "read_only"

# SECTION - NO CHANGE REQUIRED - NO CHANGES ARE REQUIRED

# Default Network Settings: (NO CHANGE REQUIRED)
nodegrid_enable_ipv4_ip_forward: "no"
nodegrid_enable_ipv6_ip_forward: "no"
nodegrid_reverse_path_filtering: "strict_mode"
nodegrid_enable_multiple_routing_tables: "yes"
failover_enable_network_failover: "no"

# Default Audit Settings: (NO CHANGE REQUIRED)
auditing_event_enable_persistent_logs: "yes"
auditing_datalog_add_timestamp: "yes"

# System Session Logging: (NO CHANGE REQUIRED)
system_logging_enable_session_logging_alerts: "no"

# Nodegrid Authentication settings: (NO CHANGE REQUIRED)
authentication_admin_and_root_fallback_to_local_on_console: "yes"
authentication_default_group_for_remote_users: ""
authentication_enable_authentication_server_selection_based_on_realms: "yes"

# System Services: (NO CHANGE REQUIRED)
services_enable_snmp_service: "yes"

# SECTION - DO NOT CHANGE - THIS SECTION CONTAINS SETTING WHICH SHOULD NOT BE CHANGED
# Generic Ansible Settings: (DO NOT CHANGE)
ansible_user: ansible
ansible_ssh_private_key_file: /home/ansible/.ssh/id_ed25519
ansible_python_interpreter: "/usr/bin/python3"

# Generic Nodegrid Roles
nodegrid_roles:
  - local_peer

cluster_settings_cluster_mode: mesh
cluster_settings_polling_rate: 120