# Generic Ansible Settings
ansible_host: 10.0.2.135

# Generic Nodegrid Roles
nodegrid_roles:
    - local_coordinator
    - wireguard_spoke

# Nodegrid Network Settings
nodegrid_hostname: la-lc1

# Nodegrid Network Connections
network_connections:
    - name: ETH0
      ethernet_interface: eth0
      description: "MGMT"
      ipv4_mode: static
      ipv4_address: 10.0.2.135
      ipv4_bitmask: 24
    - name: ETH1
      ethernet_interface: eth1
      set_as_primary_connection: "yes"
      description: "LTE"
      ipv4_mode: static
      ipv4_address: 10.1.11.2
      ipv4_bitmask: 24
      ipv4_gateway: 10.1.11.1

# Network Failover
failover_enable_network_failover: "yes"
failover_primary_connection: "ETH0"
failover_secondary_connection: "ETH1"
failover_trigger_ip_address: 10.0.2.1

# Wireguard Settings
wireguard_failover_status: "yes"
wireguard_interfaces:
    - wireguard_hub: ny-sc1   #super_coordinator ansible hostname
      wireguard_interface_name: ny-sc1  # VPN interface name
      wireguard_interface_address: 10.21.1.11/32  #Internal IP address
    - wireguard_hub: dub-sc1    #super_coordinator ansible hostname
      wireguard_interface_name: dub-sc1 # VPN interface name
      wireguard_interface_address: 10.21.2.11/32  #Internal IP address

# Cluster Settings
cluster_settings_name: LA-CLUSTER
cluster_settings_psk: LA-NGCluster
cluster_settings_type: coordinator
cluster_settings_mode: mesh
