# #########################################################
# Hub - Create Wireguard VPN and get its Public Key
# - hub: host that acts as the Hub, i.e., listens for VPN wireguard connections
# - spoke: host that acts as the Spoke, i.e., initiates the VPN wireguard handshake connection

- name: Hub - Create Wireguard VPN and get its Public Key 
  hosts: hub
  gather_facts: false
  become: true
  tasks:
    # ##################################
    # Hub - Create Hub Wireguard VPN
    - name: Create Hub Wireguard VPN 
      block:
        - name: "Delete Wireguard VPN {{ hostvars[inventory_hostname].WG_INTERFACE_NAME }} if exists"
          zpe.nodegrid.nodegrid_cmds: 
            cmds:
              - cmd: 'delete /settings/wireguard/ {{ hostvars[inventory_hostname].WG_INTERFACE_NAME }}'
              - cmd: 'commit'
          ignore_errors: true
        - name: Add Hub Wireguard VPN
          zpe.nodegrid.nodegrid_cmds:
            cmds:
              - cmd: 'cd /settings/wireguard/'
              - cmd: 'add'
              - cmd: 'set interface_name={{ hostvars[inventory_hostname].WG_INTERFACE_NAME }}'
              - cmd: 'set interface_type=server'
              - cmd: 'set internal_address={{ hostvars[inventory_hostname].WG_INTERFACE_ADDRESS }}'
              - cmd: 'set listening_port={{ hostvars[inventory_hostname].WG_LISTENING_PORT }}'
              - cmd: 'commit'

    # ##################################
    # Hub - Get Wireguard Public Key
    - name: Hub Get Wireguard Public Key interface 
      block:
        - name: Get Hub Wireguard Public Key
          zpe.nodegrid.nodegrid_cmds:
            cmds:
            - cmd: 'show /settings/wireguard/{{ hostvars[inventory_hostname].WG_INTERFACE_NAME }}/interfaces/ public_key'
          register: wg_public_key
        - name: Export Hub Wireguard Public Key
          set_fact:
            WG_PUBLIC_KEY: "{{ wg_public_key.cmds_output[0]['stdout_lines'][1].split('= ')[1] }}"

# #######################################################
# Spoke - Create Wireguard VPN and get its Public Key
- name: Spoke - Create Wireguard VPN and get its Public Key
  hosts: spokes
  gather_facts: false
  become: true
  tasks:
    # #####################################
    # Spoke - Create Spoke Wireguard VPN
    - name: Create Spoke Wireguard VPN 
      block:
        - name: "Delete Wireguard VPN {{ hostvars[inventory_hostname].WG_INTERFACE_NAME }} if exists"
          zpe.nodegrid.nodegrid_cmds: 
            cmds:
              - cmd: 'delete /settings/wireguard/ {{ hostvars[inventory_hostname].WG_INTERFACE_NAME }}'
              - cmd: 'commit'
          ignore_errors: true
        - name: Add Spoke Wireguard VPN
          zpe.nodegrid.nodegrid_cmds:
            cmds:
              - cmd: 'cd /settings/wireguard/'
              - cmd: 'add'
              - cmd: 'set interface_name={{ hostvars[inventory_hostname].WG_INTERFACE_NAME }}'
              - cmd: 'set interface_type=client'
              - cmd: 'set internal_address={{ hostvars[inventory_hostname].WG_INTERFACE_ADDRESS }}'
              - cmd: 'commit'
    # ###################################
    # Spoke - Get Wireguard Public Key
    - name: Spoke Get Wireguard Public Key interface 
      block:
        - name: Get Spoke Wireguard Public Key
          zpe.nodegrid.nodegrid_cmds:
            cmds:
            - cmd: 'show /settings/wireguard/{{ hostvars[inventory_hostname].WG_INTERFACE_NAME }}/interfaces/ public_key'
          register: wg_public_key
        - name: Export Spoke Wireguard Public Key
          set_fact:
            WG_PUBLIC_KEY: "{{ wg_public_key.cmds_output[0]['stdout_lines'][1].split('= ')[1] }}"
    # ################################
    # Spoke - Add spoke-hub peering
    - name: Spoke Add spoke-hub peering 
      block:
        - name: Spoke add spoke-hub peering
          zpe.nodegrid.nodegrid_cmds:
            cmds:
              - cmd: 'cd /settings/wireguard/{{ hostvars[inventory_hostname].WG_INTERFACE_NAME }}/peers'
              - cmd: 'add'
              - cmd: 'set peer_name={{ hostvars[inventory_hostname].WG_INTERFACE_NAME }}-peer-{{ hostvars.hub.WG_INTERFACE_NAME }}'
              - cmd: 'set allowed_ips={{ hostvars.hub.WG_INTERFACE_ADDRESS}}'
              - cmd: 'set public_key={{ hostvars.hub.WG_PUBLIC_KEY }}'
              - cmd: 'set external_address={{ hostvars.hub.WG_EXTERNAL_IP }}:{{ hostvars.hub.WG_LISTENING_PORT }}'
              - cmd: 'set keepalive=21'
              - cmd: "set description='{{ hostvars[inventory_hostname].WG_INTERFACE_NAME }} peering with {{ hostvars.hub.WG_INTERFACE_NAME }}'"
              - cmd: 'commit'
    # ################################
    # Spoke - Setup Wireguard fail-over
    - name: Spoke Add spoke-hub peering 
      block:
        - name: Spoke - Setup Wireguard fail-over
          vars:
            - WIREGUARD_ENDPOINT_MAIN: "{{ hostvars.hub.WIREGUARD_ENDPOINT_MAIN }}"
            - WIREGUARD_ENDPOINT_BACKUP: "{{ hostvars.hub.WIREGUARD_ENDPOINT_BACKUP }}"
            - WIREGUARD_IFACE_NAME: "{{ hostvars[inventory_hostname].WG_INTERFACE_NAME }}"
            - WIREGUARD_PEER_ID: "{{ hostvars[inventory_hostname].WG_INTERFACE_NAME }}-peer-{{ hostvars.hub.WG_INTERFACE_NAME }}"
          include_role:
            name: zpe.nodegrid.site_coordinator
            tasks_from: wireguard_failover
      tags:
        - failover

# ##############################
# Hub - Add hub-spoke peering
- name: Hub - Add hub-spoke peering
  hosts: hub
  gather_facts: false
  become: true
  tasks:
    - name: Hub add hub-spokes peerings 
      block:
        - name: Hub add hub-spoke peering
          zpe.nodegrid.nodegrid_cmds:
            cmds:
              - cmd: 'cd /settings/wireguard/{{ hostvars.hub.WG_INTERFACE_NAME }}/peers'
              - cmd: 'add'
              - cmd: 'set peer_name={{ hostvars.hub.WG_INTERFACE_NAME }}-peer-{{ hostvars[item].WG_INTERFACE_NAME }}'
              - cmd: 'set allowed_ips={{ hostvars[item].WG_INTERFACE_ADDRESS}}'
              - cmd: 'set public_key={{ hostvars[item].WG_PUBLIC_KEY }}'
              - cmd: 'set keepalive=21'
              - cmd: "set description='{{ hostvars.hub.WG_INTERFACE_NAME }} peering with {{ hostvars[item].WG_INTERFACE_NAME }}'"
              - cmd: 'commit'
          with_items: "{{ groups['spokes'] }}"

# ##############################################################
# Spoke - Validate Wireguard VPN: ping the Hub from the Spoke
- hosts: spokes
  gather_facts: false
  become: true
  tasks:
    - name: Spoke Validate Wireguard VPN 
      tags:
        - validatevpn
      block:
        - name: Execute Ping from Spoke to the Hub
          ansible.builtin.shell: "ping -c 5 $(/sbin/ip --json route show  dev {{ hostvars[inventory_hostname].WG_INTERFACE_NAME }} | jq -r .[0].dst)"
          #          ansible.builtin.shell: "ping -c 5 10.0.21.1"
          register: vpn_results
          retries: 5
          delay: 5
          until: "vpn_results is not failed"
        - name: Show ping results
          debug:
            var: vpn_results.stdout_lines
