- name: Process the xlsx file block
  tags: always
  block:
    - name: Install Pandas Python module in virtual environment
      tags: always
      ansible.builtin.pip:
        name: pandas, openpyxl
        virtualenv: /tmp/device_importer/venv
        virtualenv_command: "python3 -m venv"
        state: present
    - name: Run Python Process xlsx managed devices script
      tags: always
      ansible.builtin.script: 
        cmd: files/process_xlsx_managed_devices.py --nodegrid_importer_xlsx "{{ nodegrid_importer_template_xlsx | default('~/Nodegrid_Importer_Template.xlsx') }}"
        executable: /tmp/device_importer/venv/bin/python3 
        #    - name: Clean the Python Virtual Environment
        #      tags: always
        #      ansible.builtin.file:
        #        path: /tmp/device_importer
        #        state: absent
- name: Process Managed Devices from CSVs
  tags: always
  zpe.nodegrid.import_devices:
    csv_ansible_devices: "{{ csv_ansible_devices | default('./zpe_ngm_ansible_devices.csv') }}"
    csv_ip_based: "{{ csv_ip_based | default('./zpe_ngm_ip_devices.csv') }}"
    csv_serial: "{{ csv_serial | default('./zpe_ngm_serial_devices.csv') }}"
    csv_usb: "{{ csv_usb | default('./zpe_ngm_usb_devices.csv') }}"
    csv_discovery_rules: "{{ csv_discovery_rules | default('./zpe_ngm_discovery_rules.csv') }}"
    csv_device_permissions: "{{ csv_device_permissions | default('./zpe_ngm_device_permissions.csv') }}"
    ansible_inventory_path: "{{ ansible_inventory_path | default('/etc/ansible/inventories') }}"
    ansible_inventory_hosts_filename: "{{ ansible_inventory_hosts_filename | default('imported_managed_devices.yaml') }}"
    ansible_group_name: "{{ ansible_group_name | default('imported_managed_devices') }}"
    custom_fields_prefix: "{{ custom_fields_prefix | default('cf_') }}"

