FLASK_ENV: 'development'
API_PREFIX: '/api/v1'
DEBUG: True
LOG_FILE: '/tmp/wgpeer.log'
LOG_FILE_ACCESS: '/tmp/wgpeer-access.log'
LOG_LEVEL: DEBUG
NODEGRID_URI: https://localhost
NODEGRID_USER: zpeapi
NODEGRID_KEY: UjpKWjBnFkQnKzWTCC7QEEWbgxI1zSliKw==
WIREGUARD_IFACE_NAME: wg-hub
WIREGUARD_LAN: 10.20.0.0/16
WIREGUARD_IFACE_IP: 10.20.0.1/32 
WIREGUARD_IFACE_PUBLIC_IP: 35.212.186.167
WIREGUARD_IFACE_PUBLIC_PORT: 51821
WIREGUARD_IP_RESERVED:
  - 10.20.0.1/32

