- name: Update System SNMP Settings
  tags: always
  zpe.nodegrid.snmp:
    rules: "{{ snmp_rules }}"
    system:
      syscontact: "{{ syscontact | default('admin@nodegrid') }}"
      syslocation: "{{ syslocation | default('') }}"
