- name: Add DHCP Range
  with_items: "{{ network_dhcp_range }}"
  zpe.nodegrid.dhcp_server:
    network_range:
      subnet: "{{ item.subnet | default( network_dhcp_range_subnet ) }}"
      netmask: "{{ item.netmask | default( network_dhcp_range_netmask ) }}"
      prefix: "{{ item.prefix | default( network_dhcp_range_prefix ) }}"
      length: "{{ item.length | default( network_dhcp_range_length ) }}"
      ip_address_start: "{{ item.ip_address_start | default( network_dhcp_range_ip_address_start ) }}"
      ip_address_end: "{{ item.ip_address_end | default( network_dhcp_range_ip_address_end ) }}"
