- name: Configure Switch Interface
  with_items: "{{ network_switch_interfaces }}"
  zpe.nodegrid.network_switch:
    interfaces:
      interface: "{{ item.interface }}"
      status: "{{ item.status | default( network_switch_interfaces_status ) }}"
      speed: "{{ item.speed | default( network_switch_interfaces_speed ) }}"
      port_vlan_id: "{{ item.port_vlan_id | default( network_switch_interfaces_port_vlan_id ) }}"
      description: "{{ item.description | default( network_switch_interfaces_description ) }}"