- name: Deploy a VM
  hosts: all
  become: true
          
  tasks:
    - name: Install python3 lxml module
      ansible.builtin.pip:
        name: lxml
    - name: Create VMs 
      when: "'vms' in hostvars[inventory_hostname] and hostvars[inventory_hostname].vms"
      block:
        - name: Create a VM
          include_tasks: create_vm.yaml
          loop: "{{ hostvars[inventory_hostname].vms }}"
          loop_control:
            loop_var: vm

