- hosts: all
  gather_facts: false
  collections:
    - zpe.nodegrid

  tasks:
    - name: Deploy Virtual Machines
      block:
      - name: Create VMs
        include_role:
          name: system_virtual_machine
        tags:
         - create_vms

