- name: Update System Preferences
  tags: always
  zpe.nodegrid.system:
      date_and_time:
        date_and_time: "{{ sys_date_and_time_date_and_time }}"
        server: "{{ sys_date_and_time_server }}"
        zone: "{{ sys_date_and_time_zone }}"
