- name: Add DHCP Server
  with_items: "{{ network_dhcp_servers }}" 
  zpe.nodegrid.dhcp_server:
    settings:
      protocol: "{{ item.protocol }}"
      subnet: "{{ item.subnet | default( network_dhcp_servers_subnet ) }}"
      netmask: "{{ item.netmask | default( network_dhcp_servers_netmask ) }}"
      prefix: "{{ item.prefix | default( network_dhcp_servers_prefix ) }}"
      length: "{{ item.length | default( network_dhcp_servers_length ) }}"
      domain: "{{ item.domain | default( network_dhcp_servers_domain ) }}"
      domain_name_servers: "{{ item.domain_name_servers | default( network_dhcp_servers_domain_name_servers ) }}"
      #router_ip: "{{ item.router_ip | default( network_dhcp_servers_router_ip ) }}"
      lease_time: "{{ item.lease_time | default( network_dhcp_servers_lease_time ) }}"
      wifi_controller_ip: "{{ item.wifi_controller_ip | default( network_dhcp_servers_wifi_controller_ip ) }}"