- name: Update System Services
  tags: always
  zpe.nodegrid.services:
    debug: "{{ debug | default(false)}}"
    services:
      enable_detection_of_usb_devices: "{{ enable_detection_of_usb_devices | default('') }}"
      enable_rpc: "{{ enable_rpc | default('') }}"
      enable_grpc: "{{ enable_grpc | default('') }}"
      grpc_port:  "{{ grpc_port | default('') }}"
      enable_ftp_service: "{{ enable_ftp_service | default('') }}"
      enable_snmp_service: "{{ enable_snmp_service | default('') }}"
      enable_telnet_service_to_nodegrid: "{{ enable_telnet_service_to_nodegrid | default('') }}"
      telnet_tcp_port: "{{ telnet_tcp_port | default('') }}"
      enable_telnet_service_to_managed_devices: "{{ enable_telnet_service_to_managed_devices | default('') }}"
      enable_icmp_echo_reply: "{{ enable_icmp_echo_reply | default('') }}"
      enable_icmp_secure_redirects: "{{ enable_icmp_secure_redirects | default('') }}"
      enable_usb_over_ip: "{{ enable_usb_over_ip | default('') }}"
      enable_search_engine: "{{ enable_search_engine | default('') }}"
      enable_dashboards: "{{ enable_dashboards | default('') }}"
      enable_telegraf: "{{ enable_telegraf | default('') }}"
      enable_services_status_page: "{{ enable_services_status_page | default('') }}"
      enable_reboot_on_services_status_page: "{{ enable_reboot_on_services_status_page | default('') }}"
      enable_keepalived: "{{ enable_keepalived | default('') }}"
      show_warning_for_expiring_root_ca: "{{ show_warning_for_expiring_root_ca | default('') }}"
      enable_core_dump_collection: "{{ enable_core_dump_collection | default('') }}"
      enable_vmware_manager: "{{ enable_vmware_manager | default('') }}"
      enable_docker: "{{ enable_docker | default('') }}"
      docker_directory_location: "{{ docker_directory_location | default('') }}"
      enable_qemu|kvm: "{{ enable_qemu | default('') }}"
      cluster_tcp_port: "{{ cluster_tcp_port | default('') }}"
      auto_cluster_enroll: "{{ auto_cluster_enroll | default('') }}"
      search_engine_tcp_port: "{{ search_engine_tcp_port | default('') }}"
      enable_search_engine_high_level_cipher_suite: "{{ enable_search_engine_high_level_cipher_suite | default('') }}"
      enable_vm_serial_access: "{{ enable_vm_serial_access | default('') }}"
      vm_serial_port: "{{ vm_serial_port | default('') }}"
      vmotion_timeout: "{{ vmotion_timeout | default('') }}"
      enable_zero_touch_provisioning: "{{ enable_zero_touch_provisioning | default('') }}"
      enable_bluetooth: "{{ enable_bluetooth | default('') }}"
      bluetooth_display_name: "{{ bluetooth_display_name | default('') }}"
      bluetooth_discoverable_mode: "{{ bluetooth_discoverable_mode | default('') }}"
      enable_pxe: "{{ enable_pxe | default('') }}"
      device_access_per_user_group_authorization: "{{ device_access_per_user_group_authorization | default('') }}"
      enable_autodiscovery: "{{ enable_autodiscovery | default('') }}"
      dhcp_lease_per_autodiscovery_rules: "{{ dhcp_lease_per_autodiscovery_rules | default('') }}"
      block_host_with_multiple_authentication_failures: "{{ block_host_with_multiple_authentication_failures | default('') }}"
      block_host_period_host_will_stay_blocked: "{{ block_host_period_host_will_stay_blocked | default('') }}"
      block_host_timeframe_to_monitor_authentication_failures: "{{ block_host_timeframe_to_monitor_authentication_failures | default('') }}"
      block_host_number_of_authentication_failures_to_block: "{{ block_host_number_of_authentication_failures_to_block | default('') }}"
      block_host_whitelisted_ip_addresses: "{{ block_host_whitelisted_ip_addresses | default('') }}"
      block_account_with_multiple_authentication_failures: "{{ block_account_with_multiple_authentication_failures | default('') }}"
      block_account_period_account_will_stay_blocked: "{{ block_account_period_account_will_stay_blocked | default('') }}"
      block_account_timeframe_to_monitor_authentication_failures: "{{ block_account_timeframe_to_monitor_authentication_failures | default('') }}"
      block_account_number_of_authentication_failures_to_block: "{{ block_account_number_of_authentication_failures_to_block | default('') }}"
      block_account_show_message_when_account_is_locked: "{{ block_account_show_message_when_account_is_locked | default('') }}"
      enable_console_access: "{{ enable_console_access | default('') }}"
      allow_root_console_access: "{{ allow_root_console_access | default('') }}"
      rescue_mode_require_authentication: "{{ rescue_mode_require_authentication | default('') }}"
      password_protected_boot: "{{ password_protected_boot | default('') }}"
      boot_password: "{{ boot_password | default('') }}"
      ssh_allow_root_access: "{{ ssh_allow_root_access | default('') }}"
      ssh_tcp_port: "{{ ssh_tcp_port | default('') }}"
      ssh_ciphers: "{{ ssh_ciphers | default('') }}"
      ssh_macs: "{{ ssh_macs | default('') }}"
      ssh_kexalgorithms: "{{ ssh_kexalgorithms | default('') }}"
      enable_http_access: "{{ enable_http_access | default('') }}"
      http_port: "{{ http_port | default('') }}"
      enable_https_access: "{{ enable_https_access | default('') }}"
      https_port: "{{ https_port | default('') }}"
      redirect_http_to_https: "{{ redirect_http_to_https | default('') }}"
      enable_https_file_repository: "{{ enable_https_file_repository | default('') }}"
      tlsv1.3: "{{ tlsv1_3 | default('') }}"
      tlsv1.2: "{{ tlsv1_2 | default('') }}"
      tlsv1.1: "{{ tlsv1_1 | default('') }}"
      tlsv1: "{{ tlsv1 | default('') }}"
      cipher_suite_level: "{{ cipher_suite_level | default('') }}"
      custom_cipher_suite: "{{ custom_cipher_suite | default('') }}"
      frr_enable_bgp: "{{ frr_enable_bgp | default('') }}"
      frr_enable_isis: "{{ frr_enable_isis | default('') }}"
      frr_enable_ospfv2: "{{ frr_enable_ospfv2 | default('') }}"
      frr_enable_ospfv3: "{{ frr_enable_ospfv3 | default('') }}"
      frr_enable_path: "{{ frr_enable_path | default('') }}"
      frr_enable_rip: "{{ frr_enable_rip | default('') }}"
      frr_enable_vrrp: "{{ frr_enable_vrrp | default('') }}"
    zpe_cloud:
      enable_zpe_cloud: "{{ enable_zpe_cloud | default('') }}"
      enable_remote_access: "{{ enable_remote_access | default('') }}"
