- name: Add Authorization Group "{{ group['name'] | default('') }}" and Devices Permissions
  tags: always
  zpe.nodegrid.security:
    authorization:
      name: "{{ group['name'] }}"
      devices:  "{{ group['devices'] }}"
