- name: Iteration "{{ i }}" | Add Managed Device "{{ device['name'] | default('') }}"
  tags: always
  vars:
    device_access: "{{ device | combine({ 'custom_fields': omit, 'management': omit, 'logging': omit, 'commands': omit }) }}"
    device_custom_fields: "{{ device.custom_fields | default([]) }}"
    device_management: "{{ device.management | default({}) }}"
    device_logging: "{{ device.logging | default({}) }}"
    device_commands: "{{ device.commands | default([]) }}"
  zpe.nodegrid.managed_devices:
    timeout: "{{ nodegrid_timeout | default(60) }}"
    max_retries: "{{ add_device_retries | default(3) }}"
    device:
      access: "{{ device_access }}"
      custom_fields: "{{ device_custom_fields }}"
      management: "{{ device_management }}"
      logging: "{{ device_logging }}"
      commands: "{{ device_commands }}"
  register: result
  until: "'msg' not in result or 'The system configuration has been changed. Please revert.' not in result['msg']"
  retries: "{{ add_device_retries | default(3) }}"
  delay: "{{ add_device_delay | default(0) }}" 
