- name: Add managed devices
  tags: always
  when: managed_devices is defined
  include_tasks: add_managed_device.yml
  loop: "{{ managed_devices }}"
  loop_control:
    loop_var: device

- name: Configure SSH keys
  tags: always
  when: managed_devices is defined
  include_tasks: setup_ssh_keys.yml
  loop: "{{ managed_devices }}"
  loop_control:
    loop_var: device

- name: Restart 'spmmulticonn' service
  ansible.builtin.service:
    name: spmmulticonn
    state: restarted
  become: true

- name: Add Discovery Rules
  tags: always
  when: discovery_rules is defined
  include_tasks: add_discovery_rule.yml
  loop: "{{ discovery_rules }}"
  loop_control:
    loop_var: discovery_rule

- name: Add Authorizations Groups and Devices Permissions
  tags: always
  when: authorization is defined
  include_tasks: add_authorization.yml
  loop: "{{ authorization }}"
  loop_control:
    loop_var: group
