- name: Add managed devices
  tags: always
  when: managed_devices is defined
  block:
    - name: Add a managed device
      include_tasks: add_managed_device.yml
      tags: always
      loop: "{{ managed_devices }}"
      loop_control:
        loop_var: device
- name: Add Discovery Rules
  tags: always
  when: discovery_rules is defined
  block:
    - name: Add a Discovery Rule
      include_tasks: add_discovery_rule.yml
      tags: always
      loop: "{{ discovery_rules }}"
      loop_control:
        loop_var: discovery_rule
