---
# Requirements: None
# purpose:
# This playbook can be used to grant the ansible user sudoers permissions
# The module uses it's own ssh connection which is not dependent on a current ansible connection.
# The use case is to easly configure a default Nodegrid appliance, so that it can be used with ansible
#
- hosts: all
  name: Configure ZPE Out Of Box - Factory Default
  gather_facts: false
  collections:
    - zpe.nodegrid
  vars_prompt:
    - name: nodegrid_user
      prompt: Enter Username for the connection
      default: admin
      private: false
    - name: current_password
      prompt: Provide a current password for the user
      private: true
    - name: ssh_port
      prompt: Enter SSH port
      default: 22
      private: false

  tasks:
    - name: Provide sudoers permission to ansible user
      zpe.nodegrid.setup:
        username: "{{ nodegrid_user }}"
        password: "{{ current_password }}"
        ssh_port: "{{ ssh_port }}"
        ssh_key_user: "ansible"
        ssh_key_user_sudoers: true
