---
# Requirements: None
# Purpose:
# - Install a defined user's ssh public key into a specific target node ssh authorized keys
#
- hosts: all
  name: Configure ZPE Out Of Box - Wireguard Spoke profile
  gather_facts: false
  collections:
    - zpe.nodegrid

  vars_prompt:
    - name: nodegrid_user
      prompt: Enter Username for the connection
      default: admin
      private: false
    - name: current_password
      prompt: Provide a password for the user
      private: true
    - name: ssh_key_user
      prompt: Provide username to which the ssh_key should be installed
      default: ansible
      private: false
    - name: ssh_key_type
      prompt: Provide ssh key type that is used (dsa | ecdsa | ecdsa-sk | ed25519 | ed25519-sk | rsa)?
      default: rsa
      private: false
    - name: ssh_key
      prompt: Enter a user's ssh public key to access ansible user via ssh
      private: false
    - name: ssh_port
      prompt: Enter ssh port
      default: 22
      private: false      
    - name: ansible_sudoers
      prompt: Add user to sudoers (True | False)?
      default: true
      private: false

  tasks:
   - block:
      - name: Install a ssh_key for a user
        zpe.nodegrid.setup:
            username: "{{ nodegrid_user }}"
            password: "{{ current_password }}"
            ssh_key_user: "{{ ssh_key_user }}"
            ssh_key_type: "{{ ssh_key_type }}"
            ssh_key: "{{ ssh_key }}"
            ssh_port: "{{ ssh_port }}"
            ansible_sudoers: "{{ ansible_sudoers }}"

      - name: Validate Connection
        ping:
