- hosts: all
  gather_facts: false
  collections:
    - zpe.nodegrid
  vars:
    lab_nsr_snmp: "RACK1"
    lab_nsr_sn: "123456789"

  tasks:
    - name: Get Nodegrid Facts
      zpe.nodegrid.facts:

    - name: setting Super Coordinator connection
      include_role:
        name: site_coordinator
