- hosts: all
  gather_facts: false
  collections:
    - zpe.nodegrid

  tasks:
    - name: Configure Nodegrid
      block:
      - name: Setup Audit Settings
        include_role:
          name: auditing
        tags:
         - auditing

      - name: Setup System Services
        include_role:
          name: system_services
        tags:
         - services

      - name: Setup Network Settings
        include_role:
          name: network_settings
        tags:
         - network_settings

      - name: Setup IPv4 Firewall Settings
        include_role:
          name: network_firewallv2
        tags:
          - firewall

      - name: Setup System Preferences
        include_role:
          name: system_preferences
        tags:
          - system_preferences

      - name: Setup System Authentication
        include_role:
          name: system_authentication
        tags:
          - authentication

      - name: Setup System SNMP Settings
        include_role:
          name: system_snmp_settings
        tags:
          - snmp_settings

# #################### SDP
    - name: Network Connections
      block:
      - name: Setup Network Connections
        include_role:
          name: network_connections
        tags:
          - network_connections

    - name: Configure DHCP Server
      tags:
        - dhcp-server
      block:
        - name: Add ipv4 DHCP Server
          include_role:
            name: network_dhcp_server

        - name: Add ipv4 DHCP Network range
          include_role:
            name: network_dhcp_range
    
    - name: Configure Switch
      tags:
        - switch
      block:
        - name: Configure Switch Interfaces
          vars:
            network_switch_interfaces: "{{ switch.interfaces }}"
          include_role:
            name: network_switch_interfaces

        - name: Configure Switch VLANs
          vars:
            network_switch_vlan: "{{ switch.vlans }}"
          include_role:
            name: network_switch_vlan
        
        - name: Configure Switch Backplane interfaces
          vars:
            network_switch_backplane: "{{ switch.backplane }}"
          include_role:
            name: network_switch_backplane

