- become: true
  block:
  - name: Get source disk file stats
    connection: local
    ansible.builtin.stat:
      path: "{{ disk.file_source }}"
      get_checksum: "{{ disk.file_source_get_checksum | default('yes') }}"
    register: st_src
    failed_when: not st_src.stat.exists
  - name: Get destination disk file stats (in images_cache if exists)
    ansible.builtin.stat:
      path: "{{ libvirt_resources_path }}/{{ images_cache }}/{{ disk.file_cache_name }}"
      get_checksum: "{{ disk.file_get_checksum | default('yes') }}"
    register: st_dest
  - name: Copy file disk from control node to remote node images_cache
    ansible.builtin.copy:
      src: "{{ disk.file_source }}"
      dest: "{{ libvirt_resources_path }}/{{ images_cache }}/{{ disk.file_cache_name }}"
      checksum: "{{ st_src..stat.checksum }}"
    when: not st_dest.stat.exists or st_src.stat.checksum != st_dest.stat.checksum
  - name: Clear stats vars
    ansible.builtin.set_fact:
      st_src:
      st_dest:
