---
- hosts: all
  gather_facts: false
  collections:
    - zpe.nodegrid
  vars:
    backup_filename: "{{ inventory_hostname }}.tar.gz"
    local_backup_folder: "/var/local/file_manager/admin_group/backup/"

  tasks:
    - name: Execute a local Backup
      zpe.nodegrid.nodegrid_cmds:
         cmds:
           - cmd: 'save_settings'
           - cmd: 'set filename={{ backup_filename }}'
           - cmd: 'save'
      register: output

    - name: Check that Backup was created
      stat:
        path: "/backup/{{ backup_filename }}"
      register: backup_file

    - name: Assert that file exists
      assert:
        that: "backup_file.stat.exists == true"

    - name: Adjust File permissions
      file:
        path: "/backup/{{ backup_filename }}"
        state: file
        mode: '0755'
      become: True

    - name: Create backup directory
      file:
        path: {{ local_backup_folder }}
        state: directory
        mode: '0660'

    - name: Copy file to local directory called backup
      fetch:
        src: "/backup/{{ backup_filename }}"
        dest: "{{ local_backup_folder }}"
        flat: true
        become: True
