- hosts: all
  gather_facts: true
  collections:
    - zpe.nodegrid

  tasks:
    - name: Get Nodegrid Facts
      zpe.nodegrid.nodegrid_facts:

    - name: Show Ansible and Nodegrid facts
      debug:
        var: ansible_facts
