- hosts: all
  gather_facts: false
  collections:
    - zpe.nodegrid

  tasks:
    - name: Read state
      zpe.nodegrid.nodegrid_read_state:
         read_options:
          path: '/settings/network_connections/BRIDGE1'
          options: interface
          #path: '/settings/auditing/destinations/snmptrap'
          #options: ['snmptrap_transport_protocol'] # optional parameter to get specific option
      register: _connection_interface
      failed_when: _connection_interface.output.read_options.results.options | length == 0

    - name: Display Result
      debug:
        msg: "{{ (_connection_interface.output.read_options.results.options).interface }}"
